flameshot-org/flameshot-org.github.io

data/getting-start.md

Add Solus to the "Getting Started" document (available packages), as it is possible to get it directly from its package manager.

Add Solus to available packages

---

docs/getting-started.md

Fixes non-absolute link on https://flameshot.org/getting-started/ leading to broken URL.

Fix broken link to Github issues page.

---

docs/guide/key-bindings.md

Hey! I noticed that the configuration file was renamed, but the old links remained on the site. I changed the links to the actual ones.

Update KDE shortcuts config links

---

content/docs/installation/installation-linux.md
sass/common/_global.scss
templates/index.html

- fixes #50 
- added a button for the nightly builds under the Linux tab on the index page
- added underline text decoration to the links in the main content of the docs section

fix broken link, and styling the links in main docs

---

content/docs/installation/installation-linux.md
sass/components/_code.scss

This still has the caveat that if the `<code>` is under the `<li>`  block it will not get this style. but the reason is that I couldn't manage to make the `li code {}` specific to `<li><code>blah blah</code></li>` and it was still getting applied to `<li><pre><code>blah blah</code></pre></li>`. Perhaps in some later versions we can fix this.

some minor styling for the inline code blocks

---

content/docs/guide/faq.md
content/docs/installation/installation-osx.md
sass/components/_code.scss
templates/index.html

The SCSS was improper and the html code tags that were inside `<li>` or `<ol>` was not detected to apply the background color and radius and now it works.
also all the instances of "macOs" were corrected to "macOS".

SCSS fix and typo corrected

---

content/docs/guide/key-bindings.md
content/docs/guide/troubleshooting.md
content/docs/installation/installation-linux.md
content/docs/installation/source-code.md

This is mostly typos and grammar mistakes, although I also took the liberty of changing the format of two pages to make them more consistent overall.
- In `key-bindings` I simply fixed the shortcuts table.
- In `installation-linux.md` I changed the format of Distro-Agnostic AppImage steps to make it more readable.

Fix typos and formatting

---

templates/macros/head.html

This happens in the homepage.
You probably don't want Facebook to be marked as your author :) 
Since other metadata is missing (like meta description) this is sometimes used in SEO previews. See for example in Telegram

Update head.html to only include article:publisher and article:author if the respective variable is set

---

config.toml

Currently this is empty 
This will cause search engines to pull this value from the page, leading to some unwanted description to be shown. See the attached screenshot for example:

Set HTML metadata description to some sensible value

---

content/docs/guide/wayland-help.md

Hey, I had this issue on gnome, the solution is the same as described in "Can't screen anything on Wayland KDE", so I just copied that into the gnome section too

Gnome Wayland Help: Add solution for missing xdg-desktop-portal

---

templates/macros/header.html

The toggle theme button on the header of the page has an outline on the user's focus. I have removed the `btn-link` class and handled the padding using `tailwindCSS` hence the outline has been removed.

style(header): remove toggle theme button outline on focus

---

templates/index.html

Noticed and fixed a teeny typo.

Uppercase `h` in GitHub

---

templates/index.html

Make it easier for people to download Flameshot binaries for their platform. This PR dynamically sets the download button links to binaries from the latest release using the Github API.
Fixes #115 
- Please let me know if you prefer the js code in it's own file or if inline with the html is ok.

Implement dynamically setting download links to latest release

---

content/docs/advanced/commandline-options.md

Hi, I noticed a few typos that I thought I could help by fixing.

Fix a few typos and wording consistency issues in the CLI documentation

---

content/docs/guide/issue-reporting.md
content/docs/guide/troubleshooting.md

Snopyta's privatebin instruction was also removed because they changed the maximum expiration time to only 1 month which is very short and having dbus info is sometimes vital to address an issue.

[update] the dbus-monitor instructions was updated

---

.github/workflows/build.yml
templates/docs/section.html

Adds support for developer docs. The developer docs are maintained on the main flameshot repo, but they need to be deployed with a workflow here.
This PR adds a reference to the documentation in the Docs section and a workflow that will re-apply the developer docs during the build_and_deploy job.
In order to add a reference to the developer docs in the Docs section, I edited the `templates/docs/section.html` template to hardcode the section there, because that's the only way I know how. Is that OK? If you know of a better way, please tell me.

Add developer docs

---

content/docs/guide/wayland-help.md

This is to address the furious Gnome user's comments, especially:
- https://github.com/flameshot-org/flameshot/issues/3365
- https://github.com/flameshot-org/flameshot/issues/3326

adds instructions to bypass a Gnome issue

---

content/docs/overview/overview.md

Updates hyperlinks on https://flameshot.org/docs/overview/overview that currently point to 404s.

Update hyperlinks on Overview page

---

.github/workflows/build.yml

Hi :wave: 
From what I can tell, the `developer-docs` branch was renamed to `dev-docs-staging` around the time of this commit: https://github.com/flameshot-org/flameshot-org.github.io/commit/14ae19351a1646fa1e71c1d366afda6cefa4b42c
This PR will make CI pass :partying_face:

CI - Fix zola-deploy action

---

content/docs/_index.md
content/docs/advanced/_index.md
content/docs/guide/_index.md
content/docs/installation/_index.md
content/docs/more/_index.md
content/docs/overview/_index.md
content/donate/_index.md

I encountered an error when i tried to install this locally on my Win11 pc with zola 0.20.0
Error:
```
Building site...
Error: Failed to serve the site
Error: Error when parsing front matter of section `\\?\T:\flameshot-org.github.io\content\docs\_index.md`
Error: Reason: TOML parse error at line 4, column 1
|
3 | time = 2021-05-01T08:00:00+00:00
| ^^^^
unknown field `updated`, expected one of `title`, `description`, `sort_by`, `weight`, `draft`, `template`, `paginate_by`, `paginate_reversed`, `paginate_path`, `insert_anchor_links`, `render`, `redirect_to`, `in_search_index`, `transparent`, `page_template`, `aliases`, `generate_feeds`, `extra`
```
```
Building site...
Error: Failed to serve the site
Error: Error when parsing front matter of section …
```

Removed unsupported fields date, updated

---

config.toml

I encountered an error when i tried to install this locally on my Win11 pc with `zola 0.20.0`
Error:
```
Building site...
Error: Failed to serve the site
Error: TOML parse error at line 14, column 1
|
14 | generate_feed = true
| ^^^^^^^^^^^^^
unknown field `generate_feed`, expected one of `base_url`, `theme`, `title`, `description`, `default_language`, `languages`, `translations`, `generate_feeds`, `feed_limit`, `feed_filenames`, `hard_link_static`, `taxonomies`, `author`, `compile_sass`, `minify_html`, `build_search_index`, `ignored_content`, `ignored_static`, `mode`, `output_dir`, `preserve_dotfiles_in_output`, `link_checker`, `slugify`, `search`, `markdown`, `extra`, `generate_sitemap`, `generate_robots_txt`, `exclude_paginated_pages_in_sitemap`
```
Fix:
The following change to suit …

Update config.toml parameter to suit the latest version of zola

---

templates/macros/footer.html

This is a PR to address #170
The fix now does fetch the current time like YYYY-MM-DDTHH:MM:SS+00:00 and only use YYYY of it  in the footer.
New Footer will look like:
```
Copyright © 2017-YYYY Flameshot contributors 
```

Improved footer macro to update with current year
