data/getting-start.md

The relative link to the new page I created was not working and is now fixed.

Fixed the relative link

---

data/getting-start.md
data/issue-reporting.md

This is to help users to give us better bug reports.

Added a page to explain how to get the system information

---

docs/getting-started.md

fixed typo on getting-started.md

fixed typo

---

docs/issue-reporting.md
docs/troubleshooting.md

* Added two of the frequent issues to the troubleshooting section
* The `inxi` command was added to make it easier for users to provide uniform system information

Issue reporting and trouble shooting additions

---

docs/advanced/command-line-options.md

[add] added some explanation about the CLI structure

[fix] markdown styles for the CLI page were fixed

---

docs/index.md

I already tested the fix locally

[fix] Shortcuts link

---

docs/guide/faq.md
docs/guide/installation/installation-linux.md

Thanks to @HW71 for their investigation and [suggested solution](https://github.com/flameshot-org/flameshot/issues/1648#issuecomment-891612360)

Added a solution for the tray icon issue in Cinnamon

---

README.md
content/docs/guide/faq.md
content/docs/installation/installation-windows.md
content/docs/installation/source-code.md
templates/index.html

- Fixed some markdown formatting and styling
- Added some missing links
- Fixed some broken links

Some quick fixes

---

templates/macros/footer.html

This is since we moved to Matrix.org from Feneas.org

Updated the matrix room address

---

content/docs/guide/faq.md
content/docs/guide/key-bindings.md
content/docs/guide/troubleshooting.md
content/docs/guide/wayland-help.md
content/docs/installation/installation-osx.md
templates/index.html

- Fixes #53
- Fixes https://github.com/flameshot-org/flameshot/issues/2349
- Added a dedicated page for Wayland to aggregate all the Wayland-specific stuff there in a cohesive manner
- minor re-formatting of the markdown to make it easier to maintain

improvement of macOS and Wayland documentation

---

content/docs/guide/troubleshooting.md

Addresses the following:
https://github.com/flameshot-org/flameshot/issues/1932#issuecomment-1046835388

adds a line to macOS troubleshoot to tell user to restart

---

templates/index.html

update to the current latest version v11.0.0

Update to the current v11.0.0

---

content/docs/guide/issue-reporting.md
content/docs/guide/key-bindings.md
content/docs/installation/installation-linux.md
content/docs/overview/overview.md

see the commit messages for more granular info

Some more fixes

---

README.md
content/docs/guide/troubleshooting.md

Some updated in troubleshooting

---

templates/index.html
templates/macros/footer.html

Should change to some general word example **Latest Version** so avoid this repetitive change?

Update download section to latest v12.0.0

---

README.md

Fixed a little typo in README.md

---

templates/macros/footer.html

- donate button was added to footer
- contribution in footer now follows others style

Some fixes for footer

---

content/docs/guide/key-bindings.md

Supersedes https://github.com/flameshot-org/flameshot-org.github.io/pull/31
Updated hotkeys taken from this PR: https://github.com/flameshot-org/flameshot#1097
Ref: https://github.com/flameshot-org/flameshot/issues/1593
cc @ZetaoYang

Add hotkeys, incl. macOS + Windows global hotkeys

---

.github/workflows/build.yml

Hoping to fix the ambiguous error of https://github.com/flameshot-org/flameshot-org.github.io/runs/7977236798?check_suite_focus=true#step:4:134

updates the zola deploy Github Action

---

templates/macros/footer.html

update website copywrite year

---

content/docs/installation/installation-osx.md

Fix https://github.com/flameshot-org/flameshot/issues/3572
Content comes from https://github.com/flameshot-org/flameshot?tab=readme-ov-file#macos

Update OSX Installation for Sonoma

---

content/docs/guide/imgur_help.md

corrected spelling error in the docs

---

content/docs/guide/imgur_help.md

Few more spelling corrections found and corrected

more spelling corrections in docs

---

content/docs/installation/installation-linux.md
content/docs/installation/installation-osx.md
content/docs/installation/installation-windows.md
content/docs/installation/source-code.md
content/donate/_index.md

Correct capitalization of "GitHub"
